// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoghisqkclkzexbjahzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZ2hpc3FrY2xremV4YmphaHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODkwMjYsImV4cCI6MjA2MjU2NTAyNn0.v1rERWUgozbb4WUVbAJMhi_g_IB-OKC90zT8PxqZNWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);